image: node:10.9.0

cache:
  key: ${CI_COMMIT_REF_NAME}
  paths:
    - node_modules/

stages:
  - deploy

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - git config --global user.email "deploy@tsb.com"
  - yarn install --pure-lockfile

build:
  stage: deploy
  script:
    - PACKAGE_VERSION=$(cat package.json | grep version | head -1  | awk -F":" '{ print $2 }' | sed 's/[\",]//g')
    - git tag -a $PACKAGE_VERSION -m $PACKAGE_VERSION
    - git push origin tag $PACKAGE_VERSION
  only:
    - master